main: com.tealcube.minecraft.bukkit.facecore.FacecorePlugin
version: ${project.version}
name: Facecore
api-version: 1.17
load: STARTUP
softdepend:
  - WorldGuard
  - PlaceholderAPI
  - DiscordSRV
  - LibsDisguises
  - ProtocolLib
  - InteractiveChat
commands:
  safe-stop:
    description: Stop
    usage: /<command>
    permission: facecore.admin
  safe-restart:
    description: Restart
    usage: /<command>
    permission: facecore.admin
  unicode-reload:
    description: relod placeholders
    usage: /<command>
    permission: facecore.admin
  toasty:
    description: mmmmmstroknke
    usage: /<command>
    permission: facecore.admin
